export const mockProcessedData = [
  {
    missionName: 'Starlink-15 (v1.0)',
    launchDateTime: new Date('2020-10-24T15:31:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['SpaceX'],
    missionPatchImgUrl: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
  },
  {
    missionName: 'Sentinel-6 Michael Freilich',
    launchDateTime: new Date('2020-11-21T17:17:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['NASA'],
    missionPatchImgUrl: null,
  },
  {
    missionName: 'Crew-1',
    launchDateTime: new Date('2020-11-16T00:27:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['NASA (CCtCap)'],
    missionPatchImgUrl: 'https://i.imgur.com/t5R4BAQ.png',
  },
  {
    missionName: 'GPS III SV04 (Sacagawea)',
    launchDateTime: new Date('2020-11-05T23:24:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['United States Space Force'],
    missionPatchImgUrl: 'https://i.imgur.com/Ehe9AgY.png',
  },
  {
    missionName: 'Starlink-14 (v1.0)',
    launchDateTime: new Date('2020-10-24T15:31:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['SpaceX'],
    missionPatchImgUrl: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
  },
  {
    missionName: 'Starlink-13 (v1.0)',
    launchDateTime: new Date('2020-10-18T12:25:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['SpaceX'],
    missionPatchImgUrl: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
  },
  {
    missionName: 'Starlink-12 (v1.0)',
    launchDateTime: new Date('2020-10-06T11:29:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['SpaceX'],
    missionPatchImgUrl: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
  },
  {
    missionName: 'Starlink-11 (v1.0)',
    launchDateTime: new Date('2020-09-03T12:46:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['SpaceX'],
    missionPatchImgUrl: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
  },
  {
    missionName: 'SAOCOM 1B, GNOMES-1, Tyvak-0172',
    launchDateTime: new Date('2020-08-30T23:18:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['CONAE'],
    missionPatchImgUrl: 'https://images2.imgbox.com/43/33/36WPntCu_o.png',
  },
  {
    missionName: 'Starlink-10 (v1.0) & SkySat 19-21',
    launchDateTime: new Date('2020-08-18T14:31:00.000Z'),
    rocketType: 'FT',
    coresLandingAttempt: true,
    coresLandingSuccessful: true,
    customers: ['SpaceX'],
    missionPatchImgUrl: 'https://images2.imgbox.com/d2/3b/bQaWiil0_o.png',
  },
];
